import Head from 'next/head';
import Header from '../components/Header/Header.js';
import Navbar from '../components/Navbar/Navbar.js';
import About from '../components/About/About.js';
import Services from '../components/Services/Services.js';
import Clients from '../components/Clients/Clients.js';
import Counters from '../components/Counters/Counters.js';
import Works from '../components/Works/Works.js';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>CofCof Studios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo_cofcof.svg" />
      </Head>

      <main>
        <Navbar />
        <Header />
        <About />
        <Services />
        <Clients />
        <Counters />
        <Works />
      </main>
    </div>
  )
}

export default MyApp
